# DVC Pipeline Definition for Cardekho V5.0
# ==========================================
# This file defines the ML pipeline stages with their dependencies and outputs.
# DVC uses this to create a dependency graph and track reproducibility.

stages:
  process_data:
    cmd: >-
      python src/data/process_data.py
      --input data/raw/cardekho_v3.csv
      --output data/processed/processed_cars.csv
    deps:
      - data/raw/cardekho_v3.csv
      - src/data/process_data.py
    outs:
      - data/processed/processed_cars.csv

  build_features:
    cmd: >-
      python src/features/build_features.py
      --input data/processed/processed_cars.csv
      --output-data data/processed/featured_cars.csv
      --output-preprocessor models/preprocessor.pkl
    deps:
      - data/processed/processed_cars.csv
      - src/features/build_features.py
    outs:
      - data/processed/featured_cars.csv
      - models/preprocessor.pkl
  train_model:
    cmd: >-
      python src/models/train_model.py
      --input data/processed/featured_cars.csv
      --output-model models/model.pkl
      --output-metrics metrics/scores.json
      --n-estimators ${train.n_estimators}
      --learning-rate ${train.learning_rate}
      --max-depth ${train.max_depth}
      --reg-lambda ${train.reg_lambda}
      --reg-alpha ${train.reg_alpha}
      --subsample ${train.subsample}
      --colsample-bytree ${train.colsample_bytree}
      --min-child-weight ${train.min_child_weight}
      --gamma ${train.gamma}
      --test-size ${train.test_size}
      --random-state ${train.random_state}
      --target ${train.target_col}
    deps:
      - data/processed/featured_cars.csv
      - src/models/train_model.py
    params:
      - train.n_estimators
      - train.learning_rate
      - train.max_depth
      - train.reg_lambda
      - train.reg_alpha
      - train.subsample
      - train.colsample_bytree
      - train.min_child_weight
      - train.gamma
      - train.test_size
      - train.random_state
      - train.target_col
    outs:
      - models/model.pkl
    metrics:
      - metrics/scores.json:
          cache: false