# DVC Pipeline Definition for Used Car Dynamic Pricing
# ====================================================
# This file defines the ML pipeline stages with their dependencies and outputs.
# DVC uses this to create a dependency graph and track reproducibility.

stages:
  process_data:
    cmd: >-
      python src/data/process_data.py
      --input data/raw/car_web_scraped_dataset.csv
      --output data/processed/processed_cars.csv
    deps:
      - data/raw/car_web_scraped_dataset.csv
      - src/data/process_data.py
    outs:
      - data/processed/processed_cars.csv
