# DVC Pipeline Definition for Used Car Dynamic Pricing
# ====================================================
# This file defines the ML pipeline stages with their dependencies and outputs.
# DVC uses this to create a dependency graph and track reproducibility.

stages:
  process_data:
    cmd: >-
      python src/data/process_data.py
      --input data/raw/car_web_scraped_dataset.csv
      --output data/processed/processed_cars.csv
    deps:
      - data/raw/car_web_scraped_dataset.csv
      - src/data/process_data.py
    outs:
      - data/processed/processed_cars.csv

  build_features:
    cmd: >-
      python src/features/build_features.py
      --input data/processed/processed_cars.csv
      --output-data data/processed/featured_cars.csv
      --output-preprocessor models/preprocessor.pkl
    deps:
      - data/processed/processed_cars.csv
      - src/features/build_features.py
    outs:
      - data/processed/featured_cars.csv
      - models/preprocessor.pkl
  train_model:
    cmd: >-
      python src/models/train_model.py
      --input data/processed/featured_cars.csv
      --output-model models/model.pkl
      --output-metrics metrics/scores.json
      --n-estimators ${train.n_estimators}
      --max-depth ${train.max_depth}
      --test-size ${train.test_size}
      --random-state ${train.random_state}
      --target ${train.target_col}
    deps:
      - data/processed/featured_cars.csv
      - src/models/train_model.py
    params:
      - train.n_estimators
      - train.max_depth
      - train.test_size
      - train.random_state
      - train.target_col
    outs:
      - models/model.pkl
    metrics:
      - metrics/scores.json:
          cache: false