# Hyperparameter Configuration - Cardekho V5.0
# ============================================

# Model Training Parameters
train:
  # XGBoost Hyperparameters - Baseline for rich dataset
  n_estimators: 1000
  learning_rate: 0.05
  max_depth: 6
  
  # Regularization (Light - dataset is clean)
  reg_lambda: 1.0
  reg_alpha: 0.5
  
  # Sampling
  subsample: 0.9
  colsample_bytree: 0.9
  
  # Tree constraints
  min_child_weight: 1
  gamma: 0.0
  
  # Train/Test Split
  test_size: 0.2
  random_state: 42
  
  # Target Variable
  target_col: price